# Site
#repository: sproogen/resume-theme
#favicon: images/Capture.ico

# Personal info
name: Samhita Marri
title: Research Assistant at the University of Illinois, Urbana-Champaign
email: marri2@illinois.edu
# website: www.github.com/sproogen/resume-theme

# Social links
# twitter_username: m_samhita
github_username:  samhita-m
# dribbble_username: jekyll
# facebook_username: Samhita Marri
# flickr_username: jekyll
#instagram_username: samhita_marri
linkedin_username: linkedin.com/in/samhita-marri
# pinterest_username: sm
#youtube_username: Samhita M
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/dp.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm a first year PhD student at the University of Illinois, Urbana-Champaign in Electrical and Computer Engineering. I am a research assitant at Distributed Autonomous Systems Laboratory (DASLAB). I am passionate about applying computer vision and multi-agent coordination in agricultural systems. 
  I am most skilled in <mark>ROS</mark>, <mark>Python</mark>, <mark>MATLAB</mark> and <mark>C++</mark>. 

# Projects Section
# projects_title: <mark>Projects<mark>

# Experience Section
# experience_title: <mark>Experience<mark>

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in agricultural robotics, some of my other interests and hobbies are,
   - Cooking
   - Painting
   - Drums


# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
